actions:
  - action: package.install
    list:
      - git
      - gnu-sed
      - wget
      - tree
      - bat
      - jq
      - yq
      - tmux
      - cfssl
      - coreutils
      - curl
      - curl-openssl
      - sekey
      - just
      - font-fira-mono-nerd-font
