actions:
  - action: package.install
    list:
      - yarn
      - composer
      - golangci-lint
      - ngrok
      - grpcurl
      - dnsmasq
      - siege
      - neovim
      - ripgrep
      - dagger/tap/dagger
    depends:
      - languages
  - action: file.link
    from: tmux.conf
    to: {{ user.home_dir }}/.tmux.conf
  
